- name: Lookup image_id
  include: lookup.yml

- name: Send request to API (delete image)
  uri:
    url: "{{ AUTH_URL_IMS }}/v2/images/{{ image_id }}"
    method: DELETE
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    status_code: 200,201,202,203,204
  register: image_delete
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: image_delete.status == 204
  changed_when: false
  when: image_id is defined and image_id|length != 0

- debug:
    msg: "{{ image_delete }}"
